# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-21 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MarketApp', '0002_axfgoods'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxfOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.FloatField()),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.AxfUser')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='AxfOrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aog_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.AxfGoods')),
                ('aog_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderApp.AxfOrder')),
            ],
            options={
                'db_table': 'axf_ordergoods',
            },
        ),
    ]
