# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='axfordergoods',
            name='aog_num',
            field=models.IntegerField(default=1),
        ),
    ]
